/**
 * AUTO-GENERATED by server-poke.io/tools/generateTownMapData.ts — do not edit.
 * Source: Venova Adventure PBS/townmap.txt + PBS/metadata.txt (region 0).
 *
 * Grid squares are 16px on the 480x320 mapRegion0 image. Fly cells are
 * tile coordinates on the destination map (multiply by the map's cellSize).
 */

export type TownMapFlySpot = { mapId: string; cellX: number; cellY: number };

export type TownMapPoint = {
  gridX: number;
  gridY: number;
  name: string;
  poi?: string;
  fly?: TownMapFlySpot;
};

export const TOWN_MAP_GRID_PX = 16;

export const TOWN_MAP_POINTS: TownMapPoint[] = [
  {
    "gridX": 5,
    "gridY": 7,
    "name": "Pueblo Semilla",
    "poi": "Laboratorio",
    "fly": {
      "mapId": "map-essentials-013",
      "cellX": 14,
      "cellY": 15
    }
  },
  {
    "gridX": 5,
    "gridY": 5,
    "name": "Ruta 1"
  },
  {
    "gridX": 5,
    "gridY": 3,
    "name": "Ciudad Coconu",
    "poi": "Puente Libertad",
    "fly": {
      "mapId": "map-essentials-021",
      "cellX": 29,
      "cellY": 14
    }
  },
  {
    "gridX": 7,
    "gridY": 3,
    "name": "Ruta 2"
  },
  {
    "gridX": 9,
    "gridY": 3,
    "name": "Ciudad Vinifer",
    "poi": "Obelisco",
    "fly": {
      "mapId": "map-essentials-036",
      "cellX": 12,
      "cellY": 22
    }
  },
  {
    "gridX": 10,
    "gridY": 3,
    "name": "Ruta 3"
  },
  {
    "gridX": 11,
    "gridY": 3,
    "name": "Ciudad Fortuna",
    "poi": "Arco del triunfo",
    "fly": {
      "mapId": "map-essentials-047",
      "cellX": 10,
      "cellY": 30
    }
  },
  {
    "gridX": 9,
    "gridY": 2,
    "name": "Ruta 12"
  },
  {
    "gridX": 10,
    "gridY": 1,
    "name": "Pueblo Noble",
    "fly": {
      "mapId": "map-essentials-091",
      "cellX": 38,
      "cellY": 57
    }
  },
  {
    "gridX": 12,
    "gridY": 3,
    "name": "Ruta 4"
  },
  {
    "gridX": 13,
    "gridY": 4,
    "name": "Villa Caocao",
    "poi": "Guardería Pokémon",
    "fly": {
      "mapId": "map-essentials-061",
      "cellX": 16,
      "cellY": 15
    }
  },
  {
    "gridX": 13,
    "gridY": 5,
    "name": "Ruta 5"
  },
  {
    "gridX": 14,
    "gridY": 6,
    "name": "Pueblo Persea",
    "poi": "Menhir",
    "fly": {
      "mapId": "map-essentials-064",
      "cellX": 10,
      "cellY": 14
    }
  },
  {
    "gridX": 16,
    "gridY": 6,
    "name": "Ruta 6"
  },
  {
    "gridX": 17,
    "gridY": 5,
    "name": "Pueblo Bianna",
    "poi": "Gimnasio Pokémon",
    "fly": {
      "mapId": "map-essentials-074",
      "cellX": 15,
      "cellY": 26
    }
  },
  {
    "gridX": 18,
    "gridY": 6,
    "name": "Ruta 7"
  },
  {
    "gridX": 19,
    "gridY": 5,
    "name": "Ciudad Anacar",
    "poi": "Estadio",
    "fly": {
      "mapId": "map-essentials-267",
      "cellX": 16,
      "cellY": 18
    }
  },
  {
    "gridX": 20,
    "gridY": 6,
    "name": "Ruta 8"
  },
  {
    "gridX": 22,
    "gridY": 6,
    "name": "Pueblo Magi",
    "poi": "Gimnasio Pokémon",
    "fly": {
      "mapId": "map-essentials-277",
      "cellX": 52,
      "cellY": 47
    }
  },
  {
    "gridX": 19,
    "gridY": 4,
    "name": "Ruta 9"
  },
  {
    "gridX": 19,
    "gridY": 2,
    "name": "Ruta 10"
  },
  {
    "gridX": 17,
    "gridY": 2,
    "name": "Pueblo Citrus",
    "poi": "Gimnasio Pokémon",
    "fly": {
      "mapId": "map-essentials-294",
      "cellX": 69,
      "cellY": 19
    }
  },
  {
    "gridX": 15,
    "gridY": 1,
    "name": "Ruta 11"
  },
  {
    "gridX": 14,
    "gridY": 3,
    "name": "Ciudad Psidiva",
    "poi": "Gimnasio Pokémon",
    "fly": {
      "mapId": "map-essentials-043",
      "cellX": 50,
      "cellY": 77
    }
  },
  {
    "gridX": 9,
    "gridY": 5,
    "name": "Cueva Moske"
  },
  {
    "gridX": 10,
    "gridY": 3,
    "name": "Ruta 12"
  },
  {
    "gridX": 10,
    "gridY": 5,
    "name": "Ruta 13"
  },
  {
    "gridX": 11,
    "gridY": 5,
    "name": "Lago Cúmulo"
  },
  {
    "gridX": 7,
    "gridY": 4,
    "name": "Valle Carica",
    "poi": "Gimnasio Pokémon",
    "fly": {
      "mapId": "map-essentials-102",
      "cellX": 48,
      "cellY": 35
    }
  },
  {
    "gridX": 11,
    "gridY": 6,
    "name": "Pueblo Annona",
    "poi": "Bosque Perdido",
    "fly": {
      "mapId": "map-essentials-111",
      "cellX": 15,
      "cellY": 13
    }
  },
  {
    "gridX": 9,
    "gridY": 6,
    "name": "Ruta 14"
  },
  {
    "gridX": 6,
    "gridY": 6,
    "name": "Pueblo Persica",
    "poi": "Gimnasio Pokémon",
    "fly": {
      "mapId": "map-essentials-121",
      "cellX": 56,
      "cellY": 14
    }
  },
  {
    "gridX": 9,
    "gridY": 7,
    "name": "Pico Nevado"
  },
  {
    "gridX": 10,
    "gridY": 8,
    "name": "Ruta 15"
  },
  {
    "gridX": 11,
    "gridY": 8,
    "name": "Pueblo Floralis",
    "poi": "Gimnasio Pokémon",
    "fly": {
      "mapId": "map-essentials-137",
      "cellX": 22,
      "cellY": 19
    }
  },
  {
    "gridX": 12,
    "gridY": 8,
    "name": "Archipiélago Paraíso"
  },
  {
    "gridX": 19,
    "gridY": 3,
    "name": "Pueblo Melico",
    "poi": "Gimnasio",
    "fly": {
      "mapId": "map-essentials-283",
      "cellX": 53,
      "cellY": 45
    }
  },
  {
    "gridX": 13,
    "gridY": 8,
    "name": "Ruta 16",
    "fly": {
      "mapId": "map-essentials-146",
      "cellX": 24,
      "cellY": 20
    }
  },
  {
    "gridX": 14,
    "gridY": 8,
    "name": "Ruta 17"
  },
  {
    "gridX": 15,
    "gridY": 8,
    "name": "Ruta 18"
  },
  {
    "gridX": 17,
    "gridY": 8,
    "name": "Meseta Cielo",
    "poi": "Liga Venova",
    "fly": {
      "mapId": "map-essentials-156",
      "cellX": 29,
      "cellY": 18
    }
  },
  {
    "gridX": 21,
    "gridY": 10,
    "name": "Ruta 19"
  },
  {
    "gridX": 23,
    "gridY": 10,
    "name": "???"
  },
  {
    "gridX": 24,
    "gridY": 10,
    "name": "Árbol Sagrado"
  }
];

export const TOWN_MAP_POSITION_BY_MAP_ID: Record<string, { gridX: number; gridY: number }> =
  {
  "map-essentials-004": {
    "gridX": 13,
    "gridY": 12
  },
  "map-essentials-010": {
    "gridX": 23,
    "gridY": 12
  },
  "map-essentials-012": {
    "gridX": 7,
    "gridY": 3
  },
  "map-essentials-013": {
    "gridX": 5,
    "gridY": 7
  },
  "map-essentials-020": {
    "gridX": 5,
    "gridY": 5
  },
  "map-essentials-021": {
    "gridX": 5,
    "gridY": 3
  },
  "map-essentials-022": {
    "gridX": 13,
    "gridY": 12
  },
  "map-essentials-023": {
    "gridX": 15,
    "gridY": 8
  },
  "map-essentials-025": {
    "gridX": 15,
    "gridY": 8
  },
  "map-essentials-031": {
    "gridX": 14,
    "gridY": 6
  },
  "map-essentials-033": {
    "gridX": 5,
    "gridY": 3
  },
  "map-essentials-036": {
    "gridX": 9,
    "gridY": 3
  },
  "map-essentials-039": {
    "gridX": 11,
    "gridY": 6
  },
  "map-essentials-040": {
    "gridX": 11,
    "gridY": 6
  },
  "map-essentials-041": {
    "gridX": 11,
    "gridY": 7
  },
  "map-essentials-043": {
    "gridX": 24,
    "gridY": 13
  },
  "map-essentials-044": {
    "gridX": 10,
    "gridY": 3
  },
  "map-essentials-045": {
    "gridX": 11,
    "gridY": 10
  },
  "map-essentials-046": {
    "gridX": 10,
    "gridY": 3
  },
  "map-essentials-047": {
    "gridX": 11,
    "gridY": 4
  },
  "map-essentials-049": {
    "gridX": 16,
    "gridY": 10
  },
  "map-essentials-053": {
    "gridX": 17,
    "gridY": 10
  },
  "map-essentials-054": {
    "gridX": 17,
    "gridY": 10
  },
  "map-essentials-060": {
    "gridX": 12,
    "gridY": 3
  },
  "map-essentials-061": {
    "gridX": 13,
    "gridY": 4
  },
  "map-essentials-063": {
    "gridX": 13,
    "gridY": 6
  },
  "map-essentials-064": {
    "gridX": 14,
    "gridY": 6
  },
  "map-essentials-066": {
    "gridX": 12,
    "gridY": 12
  },
  "map-essentials-067": {
    "gridX": 12,
    "gridY": 12
  },
  "map-essentials-068": {
    "gridX": 12,
    "gridY": 12
  },
  "map-essentials-069": {
    "gridX": 13,
    "gridY": 13
  },
  "map-essentials-070": {
    "gridX": 13,
    "gridY": 13
  },
  "map-essentials-071": {
    "gridX": 16,
    "gridY": 5
  },
  "map-essentials-072": {
    "gridX": 18,
    "gridY": 17
  },
  "map-essentials-073": {
    "gridX": 22,
    "gridY": 16
  },
  "map-essentials-074": {
    "gridX": 17,
    "gridY": 5
  },
  "map-essentials-084": {
    "gridX": 13,
    "gridY": 4
  },
  "map-essentials-088": {
    "gridX": 14,
    "gridY": 6
  },
  "map-essentials-090": {
    "gridX": 20,
    "gridY": 13
  },
  "map-essentials-091": {
    "gridX": 20,
    "gridY": 11
  },
  "map-essentials-100": {
    "gridX": 19,
    "gridY": 15
  },
  "map-essentials-102": {
    "gridX": 7,
    "gridY": 4
  },
  "map-essentials-111": {
    "gridX": 21,
    "gridY": 16
  },
  "map-essentials-121": {
    "gridX": 17,
    "gridY": 16
  },
  "map-essentials-136": {
    "gridX": 20,
    "gridY": 18
  },
  "map-essentials-137": {
    "gridX": 20,
    "gridY": 18
  },
  "map-essentials-146": {
    "gridX": 23,
    "gridY": 18
  },
  "map-essentials-150": {
    "gridX": 24,
    "gridY": 18
  },
  "map-essentials-152": {
    "gridX": 18,
    "gridY": 11
  },
  "map-essentials-154": {
    "gridX": 25,
    "gridY": 18
  },
  "map-essentials-156": {
    "gridX": 27,
    "gridY": 19
  },
  "map-essentials-157": {
    "gridX": 29,
    "gridY": 19
  },
  "map-essentials-163": {
    "gridX": 16,
    "gridY": 14
  },
  "map-essentials-167": {
    "gridX": 29,
    "gridY": 19
  },
  "map-essentials-266": {
    "gridX": 18,
    "gridY": 6
  },
  "map-essentials-267": {
    "gridX": 19,
    "gridY": 5
  },
  "map-essentials-268": {
    "gridX": 21,
    "gridY": 6
  },
  "map-essentials-277": {
    "gridX": 22,
    "gridY": 5
  },
  "map-essentials-282": {
    "gridX": 19,
    "gridY": 4
  },
  "map-essentials-283": {
    "gridX": 19,
    "gridY": 3
  },
  "map-essentials-292": {
    "gridX": 28,
    "gridY": 12
  },
  "map-essentials-293": {
    "gridX": 27,
    "gridY": 12
  },
  "map-essentials-294": {
    "gridX": 27,
    "gridY": 12
  },
  "map-essentials-304": {
    "gridX": 14,
    "gridY": 2
  }
};
