/**
 * Generates components/generated/speciesDex.ts: the Essentials InternalName ->
 * dex number map the follower-venomon system uses to pick an overworld charset
 * (asset-storage /migration_exports/characters/<3-digit dex>.png).
 *
 * Source of truth is pokecraft-api's PostgreSQL (pokemon_species), read the
 * same way tools/load_sqlite_to_postgres.py writes it: by piping psql through
 * the pokecraft-postgres docker container. Re-run after a data reload:
 *
 *   npx ts-node tools/generateSpeciesDex.ts
 */

import { execFileSync } from "child_process";
import { writeFileSync } from "fs";
import { join } from "path";

const rows = execFileSync(
    "docker",
    [
        "exec",
        "pokecraft-postgres",
        "psql",
        "-U",
        "pokecraft",
        "-d",
        "pokecraft",
        "-tAc",
        "SELECT pokemon_id, dex_number FROM pokemon_species WHERE dex_number IS NOT NULL ORDER BY dex_number"
    ],
    { encoding: "utf8" }
)
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
        const [internalName, dex] = line.split("|");
        return { internalName, dex: Number(dex) };
    })
    .filter((row) => row.internalName && Number.isFinite(row.dex) && row.dex > 0);

if (rows.length === 0) {
    throw new Error("pokemon_species returned no rows — is pokecraft-postgres up and loaded?");
}

const lines = rows.map((row) => `    ${JSON.stringify(row.internalName)}: ${row.dex},`);

const output = `/**
 * AUTO-GENERATED by tools/generateSpeciesDex.ts from pokecraft-api PostgreSQL
 * (pokemon_species). Do not edit by hand — re-run the generator to refresh.
 *
 * Essentials InternalName -> dex number. The follower-venomon system turns
 * this into an overworld charset filename (zero-padded to 3 digits).
 */

export const SPECIES_DEX_NUMBERS: Record<string, number> = {
${lines.join("\n")}
};

/** Charset basename for a species, e.g. "PIKACHU" -> "025" (null = unknown). */
export function speciesCharsetName(internalName: string): string | null {
    const dex = SPECIES_DEX_NUMBERS[internalName.toUpperCase()];

    if (!dex) {
        return null;
    }

    return String(dex).padStart(3, "0");
}
`;

const target = join(__dirname, "..", "components", "generated", "speciesDex.ts");
writeFileSync(target, output);
console.log(`wrote ${target} (${rows.length} species)`);
