/**
 * Generates the shared town-map (region map) data from the original Venova
 * Essentials PBS files:
 *
 *   - PBS/townmap.txt   -> region-0 points (grid square, name, POI, and the
 *                          authored Fly landing spot for flyable towns)
 *   - PBS/metadata.txt  -> MapPosition (region, gridX, gridY) per map, which
 *                          places every overworld map on the region image
 *
 * Output (identical content, one copy per repo):
 *   - server-poke.io/components/townMapData.ts
 *   - client-poke.io/src/components/game/townMapData.ts
 *
 * Usage: npx ts-node tools/generateTownMapData.ts ["/path/to/Venova Adventure/PBS"]
 */
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const pbsDir = process.argv[2] ?? path.join(os.homedir(), "Downloads", "Venova Adventure", "PBS");
const REGION = 0;

function readPbs(fileName: string): string {
  return fs.readFileSync(path.join(pbsDir, fileName), "utf8").replace(/^﻿/, "");
}

// Splits a PBS value list on commas while honoring double-quoted segments.
function splitPbsValues(line: string): string[] {
  const values: string[] = [];
  let current = "";
  let inQuotes = false;
  for (const char of line) {
    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === "," && !inQuotes) {
      values.push(current.trim());
      current = "";
    } else {
      current += char;
    }
  }
  values.push(current.trim());
  return values;
}

function toPlayableMapId(essentialsId: number): string {
  return `map-essentials-${String(essentialsId).padStart(3, "0")}`;
}

type TownMapPoint = {
  gridX: number;
  gridY: number;
  name: string;
  poi?: string;
  fly?: { mapId: string; cellX: number; cellY: number };
};

// ---- townmap.txt: points of the requested region ----
const points: TownMapPoint[] = [];
let currentSection = -1;
for (const rawLine of readPbs("townmap.txt").split(/\r?\n/)) {
  const line = rawLine.trim();
  const sectionMatch = line.match(/^\[(\d+)\]$/);
  if (sectionMatch) {
    currentSection = Number(sectionMatch[1]);
    continue;
  }
  if (currentSection !== REGION || !line.startsWith("Point=")) {
    continue;
  }

  const [gridX, gridY, name, poi, flyMapId, flyX, flyY] = splitPbsValues(line.slice("Point=".length));
  if (!name) {
    continue;
  }

  const point: TownMapPoint = { gridX: Number(gridX), gridY: Number(gridY), name };
  if (poi) {
    point.poi = poi;
  }
  if (flyMapId && flyX && flyY) {
    point.fly = { mapId: toPlayableMapId(Number(flyMapId)), cellX: Number(flyX), cellY: Number(flyY) };
  }
  points.push(point);
}

// ---- metadata.txt: MapPosition per map (region-0 only) ----
const positionByMapId: Record<string, { gridX: number; gridY: number }> = {};
let currentMapId: number | null = null;
for (const rawLine of readPbs("metadata.txt").split(/\r?\n/)) {
  const line = rawLine.trim();
  const sectionMatch = line.match(/^\[(\d+)\]$/);
  if (sectionMatch) {
    currentMapId = Number(sectionMatch[1]);
    continue;
  }
  if (currentMapId === null || currentMapId === 0 || !line.startsWith("MapPosition=")) {
    continue;
  }
  const [region, gridX, gridY] = line.slice("MapPosition=".length).split(",").map(Number);
  if (region === REGION) {
    positionByMapId[toPlayableMapId(currentMapId)] = { gridX, gridY };
  }
}

const header = `/**
 * AUTO-GENERATED by server-poke.io/tools/generateTownMapData.ts — do not edit.
 * Source: Venova Adventure PBS/townmap.txt + PBS/metadata.txt (region ${REGION}).
 *
 * Grid squares are ${16}px on the 480x320 mapRegion0 image. Fly cells are
 * tile coordinates on the destination map (multiply by the map's cellSize).
 */

export type TownMapFlySpot = { mapId: string; cellX: number; cellY: number };

export type TownMapPoint = {
  gridX: number;
  gridY: number;
  name: string;
  poi?: string;
  fly?: TownMapFlySpot;
};

export const TOWN_MAP_GRID_PX = 16;

export const TOWN_MAP_POINTS: TownMapPoint[] = ${JSON.stringify(points, null, 2)};

export const TOWN_MAP_POSITION_BY_MAP_ID: Record<string, { gridX: number; gridY: number }> =
  ${JSON.stringify(positionByMapId, null, 2)};
`;

const outputs = [
  path.join(__dirname, "..", "components", "townMapData.ts"),
  path.join(__dirname, "..", "..", "client-poke.io", "src", "components", "game", "townMapData.ts"),
];

for (const output of outputs) {
  fs.writeFileSync(output, header);
  console.log(`wrote ${output}`);
}
console.log(`${points.length} points (${points.filter((p) => p.fly).length} flyable), ${Object.keys(positionByMapId).length} map positions`);
