/**
 * Generates components/generated/speciesDex.ts: the Essentials InternalName ->
 * dex number map the follower-venomon system uses to pick an overworld charset
 * (asset-storage /migration_exports/characters/<3-digit dex>.png).
 *
 * Source of truth is the ORIGINAL Venova Adventure project's PBS/pokemon.txt:
 * its `[N]` section numbers are the game's own dex numbering, which is what
 * the numbered charset files follow. Do NOT generate this from pokecraft-api
 * PostgreSQL — that holds vanilla v21.1 national dex numbers, which disagree
 * with Venova for renumbered species (the PIDGEY line, the Kalos starters,
 * SYLVEON, TYRANTRUM) and lack the custom doubled-letter species entirely
 * (BULBASAURR, CHARIZARDD, MRMIME2, ...).
 *
 *   npx ts-node tools/generateSpeciesDex.ts [path/to/PBS/pokemon.txt]
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const DEFAULT_PBS = "/home/klys/Downloads/Venova Adventure/PBS/pokemon.txt";
const source = process.argv[2] || process.env.VENOVA_PBS_POKEMON || DEFAULT_PBS;

const text = readFileSync(source, "utf8").replace(/^﻿/, "");
const sections = text.split(/^\[(\d+)\]\s*$/m);

// split() yields [preamble, num, body, num, body, ...]
const rows: Array<{ internalName: string; dex: number }> = [];

for (let i = 1; i + 1 < sections.length; i += 2) {
    const dex = Number(sections[i]);
    const body = sections[i + 1];
    const match = body.match(/^InternalName\s*=\s*(\S+)/m);

    if (match && Number.isFinite(dex) && dex > 0) {
        rows.push({ internalName: match[1].toUpperCase(), dex });
    }
}

if (rows.length === 0) {
    throw new Error(`No species sections parsed from ${source}`);
}

rows.sort((a, b) => a.dex - b.dex);

const lines = rows.map((row) => `    ${JSON.stringify(row.internalName)}: ${row.dex},`);

const output = `/**
 * AUTO-GENERATED by tools/generateSpeciesDex.ts from the Venova Adventure
 * PBS/pokemon.txt (the game's OWN dex numbering — matches the numbered
 * overworld charset files). Do not edit by hand; re-run the generator.
 *
 * Essentials InternalName -> Venova dex number. The follower-venomon system
 * turns this into an overworld charset filename (zero-padded to 3 digits).
 */

export const SPECIES_DEX_NUMBERS: Record<string, number> = {
${lines.join("\n")}
};

/** Charset basename for a species, e.g. "PIKACHU" -> "025" (null = unknown). */
export function speciesCharsetName(internalName: string): string | null {
    const dex = SPECIES_DEX_NUMBERS[internalName.toUpperCase()];

    if (!dex) {
        return null;
    }

    return String(dex).padStart(3, "0");
}
`;

const target = join(__dirname, "..", "components", "generated", "speciesDex.ts");
writeFileSync(target, output);
console.log(`wrote ${target} (${rows.length} species from ${source})`);
