/**
 * Generates the Dive surface<->underwater map pairings from the Essentials PBS
 * metadata (`DiveMap=<id>` on each surface map's section).
 *
 * Like the TM compatibility table, this is immutable game data emitted as
 * committed source (`components/generated/diveMaps.ts`) rather than a Redis
 * migration — Dive just needs to know which map a deep-water tile leads to.
 *
 * Usage:
 *   npx ts-node tools/importDiveMaps.ts [--pbs <metadata.txt path>] [--dry-run]
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";

const DEFAULT_PBS = "/home/klys/Downloads/Venova Adventure/PBS/metadata.txt";
const OUTPUT_PATH = resolve(__dirname, "../components/generated/diveMaps.ts");

/** Engine map id for an Essentials numeric map id (zero-padded to 3 digits). */
function engineMapId(essentialsId: number): string {
  return `map-essentials-${String(essentialsId).padStart(3, "0")}`;
}

function parseDivePairs(raw: string): Array<[string, string]> {
  const pairs: Array<[string, string]> = [];
  let currentSection: number | null = null;
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    const header = trimmed.match(/^\[(\d+)\]$/);
    if (header) {
      currentSection = Number(header[1]);
      continue;
    }
    const dive = trimmed.match(/^DiveMap\s*=\s*(\d+)/i);
    if (dive && currentSection !== null) {
      pairs.push([engineMapId(currentSection), engineMapId(Number(dive[1]))]);
    }
  }
  return pairs;
}

function serialize(pairs: Array<[string, string]>): string {
  const entries = pairs.map(([a, b]) => `  [${JSON.stringify(a)}, ${JSON.stringify(b)}],`).join("\n");
  return `/**
 * AUTO-GENERATED by tools/importDiveMaps.ts from Essentials PBS metadata.txt.
 * Do not edit by hand — re-run the generator to refresh.
 *
 * [surfaceMapId, underwaterMapId] pairs. Dive toggles between the two.
 */

export const DIVE_MAP_PAIRS: Array<[string, string]> = [
${entries}
];
`;
}

function main() {
  const dryRun = process.argv.includes("--dry-run");
  const pbsIndex = process.argv.indexOf("--pbs");
  const pbsPath = pbsIndex >= 0 && process.argv[pbsIndex + 1] ? process.argv[pbsIndex + 1] : DEFAULT_PBS;

  const pairs = parseDivePairs(readFileSync(pbsPath, "utf8"));
  console.log(`Parsed ${pairs.length} dive pairs from ${pbsPath}:`);
  pairs.forEach(([a, b]) => console.log(`  ${a} <-> ${b}`));

  if (dryRun) {
    console.log(`Dry run: would write ${OUTPUT_PATH}.`);
    return;
  }
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, serialize(pairs), "utf8");
  console.log(`Wrote ${OUTPUT_PATH}.`);
}

main();
