/**
 * Generates the TM/HM (MT/MO) move-compatibility table from the original
 * Essentials PBS `tm.txt`.
 *
 * `tm.txt` is 182 sections — one per teachable move — each header `[MOVEINTERNAL]`
 * followed by a single comma-joined list of the species (Essentials internal
 * names) that may learn that move from a machine. This is the authoritative
 * per-species compatibility the migration never carried into the engine.
 *
 * The output is committed source (`components/generated/tmCompatibility.ts`), not
 * a Redis section: it is immutable game data read on every teach/field check, so
 * an in-process map avoids a Redis round-trip and the designer-section sanitize
 * lifecycle. Species names are upper-cased to match the engine's
 * `pokemonProfile.essentialsId` (e.g. tm.txt `NIDORANfE` -> `NIDORANFE`).
 *
 * Usage:
 *   npx ts-node tools/importTmCompatibility.ts [--pbs <tm.txt path>] [--dry-run]
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";

const DEFAULT_PBS = "/home/klys/Downloads/Venova Adventure/PBS/tm.txt";
const OUTPUT_PATH = resolve(__dirname, "../components/generated/tmCompatibility.ts");

/** The eight field-skill (HM-style) moves that also interact with the world. */
const FIELD_SKILL_MOVES = [
  "CUT",
  "FLY",
  "SURF",
  "STRENGTH",
  "WATERFALL",
  "DIVE",
  "ROCKSMASH",
  "FLASH",
];

function parseTmTxt(raw: string): Record<string, string[]> {
  const table: Record<string, string[]> = {};
  const lines = raw.split(/\r?\n/);
  let currentMove: string | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const header = trimmed.match(/^\[(.+)\]$/);
    if (header) {
      currentMove = header[1].trim().toUpperCase();
      table[currentMove] = [];
      continue;
    }
    if (currentMove) {
      const species = trimmed
        .split(",")
        .map((name) => name.trim().toUpperCase())
        .filter((name) => name.length > 0);
      // A section may (rarely) span multiple lines — accumulate.
      table[currentMove].push(...species);
    }
  }

  // De-duplicate while preserving order.
  for (const move of Object.keys(table)) {
    table[move] = Array.from(new Set(table[move]));
  }

  return table;
}

function serialize(table: Record<string, string[]>): string {
  const moves = Object.keys(table).sort();
  const entries = moves
    .map((move) => {
      const species = table[move].map((name) => JSON.stringify(name)).join(",");
      return `  ${JSON.stringify(move)}: [${species}],`;
    })
    .join("\n");

  const fieldEntries = FIELD_SKILL_MOVES.filter((move) => table[move])
    .map((move) => `  ${JSON.stringify(move)}: TM_COMPATIBILITY[${JSON.stringify(move)}],`)
    .join("\n");

  return `/**
 * AUTO-GENERATED by tools/importTmCompatibility.ts from Essentials PBS tm.txt.
 * Do not edit by hand — re-run the generator to refresh.
 *
 * Move internal name (upper-case) -> species that may learn it from a machine
 * (upper-case Essentials internal names, matching pokemonProfile.essentialsId).
 */

export const TM_COMPATIBILITY: Record<string, string[]> = {
${entries}
};

/** The field-skill (HM-style) subset, for the six MO world interactions. */
export const FIELD_SKILL_COMPATIBILITY: Record<string, string[] | undefined> = {
${fieldEntries}
};
`;
}

function main() {
  const dryRun = process.argv.includes("--dry-run");
  const pbsIndex = process.argv.indexOf("--pbs");
  const pbsPath = pbsIndex >= 0 && process.argv[pbsIndex + 1] ? process.argv[pbsIndex + 1] : DEFAULT_PBS;

  const raw = readFileSync(pbsPath, "utf8");
  const table = parseTmTxt(raw);
  const moveCount = Object.keys(table).length;
  const totalPairs = Object.values(table).reduce((sum, list) => sum + list.length, 0);

  console.log(`Parsed ${moveCount} moves, ${totalPairs} move/species pairs from ${pbsPath}.`);
  for (const move of FIELD_SKILL_MOVES) {
    console.log(`  ${move}: ${table[move] ? `${table[move].length} species` : "MISSING"}`);
  }

  if (dryRun) {
    console.log(`Dry run: would write ${OUTPUT_PATH}.`);
    return;
  }

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, serialize(table), "utf8");
  console.log(`Wrote ${OUTPUT_PATH}.`);
}

main();
