/**
 * Generates the berry-plant growth table from the original Essentials PBS
 * `berryplants.txt` (Venova ships the pre-v19 one-line CSV format:
 * `INTERNALNAME=HoursPerStage,DryingPerHour,MinYield,MaxYield`).
 *
 * The output is committed source (`components/generated/berryPlants.ts`), not
 * a Redis section — same rationale as tools/importTmCompatibility.ts: immutable
 * game data consulted on every plant/harvest and by the growth clock, so an
 * in-process map beats a Redis round-trip.
 *
 * Also accepts the v19+ INI format ([NAME] / HoursPerStage = / Yield = a,b) so
 * a newer PBS can be dropped in without touching this tool.
 *
 * Usage:
 *   npx ts-node tools/importBerryPlants.ts [--pbs <berryplants.txt path>] [--dry-run]
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";

const DEFAULT_PBS = "/home/klys/Downloads/Venova Adventure/PBS/berryplants.txt";
const OUTPUT_PATH = resolve(__dirname, "../components/generated/berryPlants.ts");

export type BerryPlantEntry = {
  hoursPerStage: number;
  dryRatePerHour: number;
  minYield: number;
  maxYield: number;
};

function parseBerryPlants(raw: string): Record<string, BerryPlantEntry> {
  const table: Record<string, BerryPlantEntry> = {};
  const lines = raw.replace(/^﻿/, "").split(/\r?\n/);
  let current: string | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const header = trimmed.match(/^\[(.+)\]$/);
    if (header) {
      current = header[1].trim().toUpperCase();
      table[current] = { hoursPerStage: 3, dryRatePerHour: 15, minYield: 2, maxYield: 5 };
      continue;
    }
    const csv = trimmed.match(/^([A-Za-z0-9_]+)\s*=\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*$/);
    if (csv) {
      table[csv[1].toUpperCase()] = {
        hoursPerStage: Number(csv[2]),
        dryRatePerHour: Number(csv[3]),
        minYield: Number(csv[4]),
        maxYield: Number(csv[5])
      };
      current = null;
      continue;
    }
    if (current) {
      const kv = trimmed.match(/^(\w+)\s*=\s*(.+)$/);
      if (!kv) continue;
      const key = kv[1].toLowerCase();
      const value = kv[2].trim();
      if (key === "hoursperstage") table[current].hoursPerStage = Number(value);
      else if (key === "dryingperhour") table[current].dryRatePerHour = Number(value);
      else if (key === "yield") {
        const [min, max] = value.split(",").map((part) => Number(part.trim()));
        table[current].minYield = Number.isFinite(min) ? min : 1;
        table[current].maxYield = Number.isFinite(max) ? max : table[current].minYield;
      }
    }
  }

  for (const name of Object.keys(table)) {
    const entry = table[name];
    entry.minYield = Math.max(1, Math.round(entry.minYield));
    entry.maxYield = Math.max(entry.minYield, Math.round(entry.maxYield));
    entry.hoursPerStage = Math.max(1, entry.hoursPerStage);
  }
  return table;
}

function serialize(table: Record<string, BerryPlantEntry>): string {
  const entries = Object.keys(table)
    .sort()
    .map((name) => {
      const e = table[name];
      return `  ${JSON.stringify(name)}: { hoursPerStage: ${e.hoursPerStage}, dryRatePerHour: ${e.dryRatePerHour}, minYield: ${e.minYield}, maxYield: ${e.maxYield} },`;
    })
    .join("\n");

  return `/**
 * AUTO-GENERATED by tools/importBerryPlants.ts from Essentials PBS berryplants.txt.
 * Do not edit by hand — re-run the generator to refresh.
 *
 * Berry item internal name (upper-case Essentials id, matching
 * itemProfile.essentialsId) -> growth profile: real hours per growth stage
 * (a plant ripens after 4 stages), moisture drain per hour (unused: the
 * global plots are never watered) and the harvest yield range.
 */

export type BerryPlantProfile = {
  hoursPerStage: number;
  dryRatePerHour: number;
  minYield: number;
  maxYield: number;
};

export const BERRY_PLANTS: Record<string, BerryPlantProfile> = {
${entries}
};
`;
}

function main() {
  const dryRun = process.argv.includes("--dry-run");
  const pbsIndex = process.argv.indexOf("--pbs");
  const pbsPath = pbsIndex >= 0 && process.argv[pbsIndex + 1] ? process.argv[pbsIndex + 1] : DEFAULT_PBS;

  const table = parseBerryPlants(readFileSync(pbsPath, "utf8"));
  const names = Object.keys(table);
  console.log(`Parsed ${names.length} berry plants from ${pbsPath}.`);
  for (const name of names.slice(0, 3)) {
    console.log(`  ${name}: ${JSON.stringify(table[name])}`);
  }

  if (dryRun) {
    console.log(`Dry run: would write ${OUTPUT_PATH}.`);
    return;
  }

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, serialize(table), "utf8");
  console.log(`Wrote ${OUTPUT_PATH}.`);
}

main();
